import { test, expect } from '@playwright/test';
import { TOUR_DONE, waitForCommandCenter } from './helpers/hydration';

// E7.H2: the sidebar exposes the activity index and can order by it.

test.describe('Activity index in the sidebar', () => {
  test.beforeEach(async ({ page }) => { await page.addInitScript(TOUR_DONE); });
  test('rows carry an activity badge with the factors in the tooltip', async ({ page }) => {
    await page.goto('./', { waitUntil: 'load' });
    await waitForCommandCenter(page);
    const badges = page.locator('.cc-sidebar [data-testid="activity-badge"]');
    expect(await badges.count()).toBeGreaterThan(5);
    const first = badges.first();
    const text = (await first.textContent())?.trim() ?? '';
    expect(Number(text)).toBeGreaterThanOrEqual(0);
    expect(Number(text)).toBeLessThanOrEqual(100);
    await expect(first).toHaveAttribute('title', /\/100/);
  });

  test('switching to Activity orders rows by descending score and persists', async ({ page }) => {
    await page.goto('./', { waitUntil: 'load' });
    await waitForCommandCenter(page);
    const toggle = page.getByTestId('sidebar-sort');
    await expect(toggle).toBeVisible();
    await toggle.locator('[data-sort="activity"]').click();
    await expect(toggle.locator('[data-sort="activity"]')).toHaveAttribute('aria-checked', 'true');
    // Activity sort renders a flat list (no recency buckets), so DOM order is the score order.
    await expect(page.locator('.cc-sidebar .cc-feed-divider')).toHaveCount(0);
    const scores = await page.locator('.cc-sidebar .cc-feed-row [data-testid="activity-badge"]').allTextContents();
    const nums = scores.map(Number);
    expect(nums.length).toBeGreaterThan(20);
    for (let i = 1; i < nums.length; i++) expect(nums[i]).toBeLessThanOrEqual(nums[i - 1]);
    expect(nums[0]).toBeGreaterThan(nums[nums.length - 1]);
    // The choice survives a reload (read from localStorage after mount).
    await page.reload({ waitUntil: 'load' });
    await waitForCommandCenter(page);
    const after = page.getByTestId('sidebar-sort');
    await expect(after.locator('[data-sort="activity"]')).toHaveAttribute('aria-checked', 'true');
    await expect(page.locator('.cc-sidebar .cc-feed-divider')).toHaveCount(0);
    // Relevance mode buckets again.
    await after.locator('[data-sort="relevance"]').click();
    await expect(page.locator('.cc-sidebar .cc-feed-divider').first()).toBeAttached();
  });

  test('the public API index carries activity for every tracker', async ({ request }) => {
    // Generated by `npm run generate-api` (the e2e workflow runs it first);
    // a missing file is a failure, not a skip, or this test proves nothing.
    const res = await request.get('./api/v1/trackers.json');
    expect(res.ok(), 'public/api/v1/trackers.json missing — run npm run generate-api').toBe(true);
    const body = await res.json();
    const list = Array.isArray(body) ? body : body.trackers;
    expect(list.length).toBeGreaterThan(0);
    for (const t of list.slice(0, 10)) {
      expect(typeof t.activity?.score).toBe('number');
      expect(Array.isArray(t.activity?.factors)).toBe(true);
    }
  });
});
