import React from 'react';
import { Composition, staticFile } from 'remotion';
import { Video, calculateDuration } from './Video';
import { SAMPLE_DATA } from './data/types';

// Studio-only data (real headlines + base64 thumbnails). Generated by
// `npx tsx prep-studio.ts`. Falls back to SAMPLE_DATA when the file
// doesn't exist (CI / fresh clone). Studio uses this for the preview
// so the timeline shows real photos and globe; render.ts always re-runs
// fetch-breaking + thumbnail download from scratch.
let studioData: typeof SAMPLE_DATA = SAMPLE_DATA;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  studioData = require('./data/studio-data.json');
} catch { /* file optional */ }

export const RemotionRoot: React.FC = () => {
  const trackerCount = Math.min(studioData.trackers.length, 3);
  const durationInFrames = calculateDuration(trackerCount);

  return (
    <>
      <Composition
        id="WatchboardDaily"
        component={Video}
        durationInFrames={durationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          data: studioData,
          geoFeatures: [],
          earthTexture: '',
          theme: 'dark',
        }}
      />
      {/* Preview compositions for individual sections */}
      <Composition
        id="WatchboardDaily-Short"
        component={Video}
        durationInFrames={calculateDuration(1)}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          data: {
            ...studioData,
            trackers: studioData.trackers.slice(0, 1),
          },
          geoFeatures: [],
          theme: 'dark' as const,
        }}
      />
    </>
  );
};

import { registerRoot } from 'remotion';
registerRoot(RemotionRoot);
