import React from 'react';
import { Composition, staticFile } from 'remotion';
import { Video, calculateDuration } from './Video';
import { SAMPLE_DATA } from './data/types';
import { DEFAULT_SLIDE_STYLE } from './data/slide-style';

// Studio-only data (real headlines + base64 thumbnails). Generated by
// `npx tsx prep-studio.ts`. Falls back to SAMPLE_DATA when the file
// doesn't exist (CI / fresh clone). Studio uses this for the preview
// so the timeline shows real photos and globe; render.ts always re-runs
// fetch-breaking + thumbnail download from scratch.
let studioData: typeof SAMPLE_DATA = SAMPLE_DATA;
let studioGeoFeatures: unknown[] = [];
let studioEarthTexture = '';
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const bundle = require('./data/studio-data.json');
  studioData = bundle;
  studioGeoFeatures = bundle._geoFeatures ?? [];
  studioEarthTexture = bundle._earthTexture ?? '';
} catch { /* file optional */ }

export const RemotionRoot: React.FC = () => {
  const trackerCount = Math.min(studioData.trackers.length, 3);
  const durationInFrames = calculateDuration(trackerCount);

  return (
    <>
      <Composition
        id="WatchboardDaily"
        component={Video}
        durationInFrames={durationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          data: studioData,
          geoFeatures: studioGeoFeatures,
          earthTexture: studioEarthTexture,
          theme: 'dark',
          slideStyle: DEFAULT_SLIDE_STYLE,
        }}
      />
      {/* Daily Progress Brief — same component, day theme */}
      <Composition
        id="WatchboardProgress"
        component={Video}
        durationInFrames={durationInFrames}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          data: studioData,
          geoFeatures: studioGeoFeatures,
          earthTexture: studioEarthTexture,
          theme: 'day' as const,
          slideStyle: DEFAULT_SLIDE_STYLE,
        }}
      />
      {/* Single-tracker preview */}
      <Composition
        id="WatchboardDaily-Short"
        component={Video}
        durationInFrames={calculateDuration(1)}
        fps={30}
        width={1080}
        height={1920}
        defaultProps={{
          data: {
            ...studioData,
            trackers: studioData.trackers.slice(0, 1),
          },
          geoFeatures: studioGeoFeatures,
          earthTexture: studioEarthTexture,
          theme: 'dark' as const,
          slideStyle: DEFAULT_SLIDE_STYLE,
        }}
      />
    </>
  );
};

import { registerRoot } from 'remotion';
registerRoot(RemotionRoot);
